.gitmodules, Makefile, server/routes/api.go, server/routes/ui.go, server/server.go
Switched to serving `temporalio/ui` instead of poc react app 
**NOTE**:  Dealing with an issue where `go:embed` doesn't support embedding folders/files that start with `_` and `.` . This results in contents of `_app` folder not loading (js and css)
There is an accepted proposal that should address this https://github.com/golang/go/issues/43854#issuecomment-819722769
The proposal is still open
There is also a change proposed from Svelte Kit side to address this issue
https://github.com/sveltejs/kit/pull/1370#issuecomment-853306453
OSS serving of UI
Allows to use Session with AuthN in UI
1. Closes 
Ran the app:
=> Switch to serving new UI

.github/workflows/ci.yml, Makefile, server/routes/swaggerui.go, server/routes/ui.go, server/server.go
Switch to serving UI as a SPA
Fixes routing when opening the UI from sub-paths
1. Closes 
* open http://localhost:8080/namespaces/default/workflows
* verify it opens correctly and data is loading
=> Serve UI as a SPA

.github/workflows/docker.yml
Changes per-commit docker images to be tagged by shortened SHA instead of full
Before:
`docker pull temporalio/ui:sha-aa17a4aba898a43d2bd74c94088b69348bc275d1`
After:
`docker pull temporalio/ui:sha-5502441`
looks cleaner
1. Closes 
=> Shorten docker image SHA tags

server/routes/api.go, server/server.go
Adds new API, currently returning Auth enabled status:
```
$ curl http://localhost:8080/api/v1/settings
{"Auth":{"Enabled":true}}
```
Needed in UI to disable/enable Login
1. Closes 
=> Add API to return auth settings

docker/README.md, docker/config_template.yaml
Changes dockers variable names from
`TEMPORAL_ENABLE_UI` -> `TEMPORAL_UI_ENABLED`
`TEMPORAL_ENABLE_OPENAPI` -> `TEMPORAL_OPENAPI_ENABLED`
consistency with `TEMPORAL_AUTH_ENABLED` and temporal server variables
1. Closes 
=> Rename UI and OPENAPI dockerize variables

server/config/config.go, server/server.go
This PR enables optional binding to an IP address or host name.
I'd like to be able to listen on the loopback interface in Temporalite so that users don't get the `Do you want the application “temporalite” to accept incoming network connections?` alert every time they start the server.
1. Closes 
N/A
Verified no behavior changes via `go run ./cmd/server`. Tested setting the host option via Temporalite.
No probably not. We might consider adding this as a `./cmd/server` CLI option though.
=> Make host configurable

server/routes/auth.go, server/server.go
Sets cookies for UI that is also served from a different & allowed origin 
Making auth work with UI served from different origin
1. Closes 
* Start the ui-server and UI under different origins (ports work too)
* Configure auth through development.yaml file
* Navigate to UI and follow auth flow
* Verify that `auth` cookie is set in browser dev tools
=> Set auth cookie for all allowed origins

server/server.go
Adds CSRF middleware that adds CSRF cookies and validates subsequent requests
Securing against CSRF
1. Closes 
FOR requests that are determined as not safe (eg. PUT, DELETE) validated that the succeed only if client sets proper `X-CSRF-TOKEN`
=> Secure aginst CSRF

server/routes/auth.go
Adds `/auth/logout` endpoint
Allows ui client to logout
1. Closes 
tested with https://github.com/temporalio/ui/pull/231
=> Add logout endpoint

config/development.yaml, docker/README.md, docker/config_template.yaml, server/config/config.go, server/rpc/rpc.go, server/rpc/tls.go, server/server.go
Adds support for mTLS
Allows communicating with secured Temporal server
1. Closes 
1. Run Temporal server with mTLS not set. Run ui-server and verify that namespaces and other data is loaded
2. Run secured Temporal server using https://github.com/temporalio/samples-server/tree/main/tls/tls-simple
- set TLS config in development.yaml
``` yaml
tls:
сaFile: /home/USERNAME/samples-server/tls/tls-simple/certs/ca.cert
certFile: /home/USERNAME/samples-server/tls/tls-simple/certs/cluster.pem
keyFile: /home/USERNAME/samples-server/tls/tls-simple/certs/cluster.key
enableHostVerification: true
serverName: tls-sample
```
- verify namespaces and other data calls succeed
=> Support mTLS connection to Temporal server

config/development.yaml, docker/config_template.yaml, server/config/config.go, server/rpc/tls.go, server/server.go
Adds support for TLS config to be passed directly as base64 values instead of file paths
For users who prefer to inline TLS values in the config file rather than having separate files
1. Closes 
With https://github.com/temporalio/samples-server/tree/main/tls/tls-simple
- with file paths
- with base64 values
- w/o TLS
=> Support TLS config as base64 values

.github/workflows/docker.yml
Makes the release docker image push on Release event, not tag
correcting github release event name
1. Closes 
not tested, based on docs
=> Push docker image on release, not on tag

docker/config_template.yaml, server/config/config.go, server/routes/api.go
Allows to configure the default the namespace
UI will navigate to that
1. Closes 
Add `defaultNamespace: accounting` in `development.yaml`
Open Dev tools of your browser
Verify that the `settings` response contains default namespace, ex
```
{"Auth":{"Enabled":false},"DefaultNamespace":"accounting"}
``` 
=> Allow configuring default namespace for UI to navigate to

cmd/server/main.go, server/server.go, server/server_options/server_option.go, server/server_options/server_options.go
The `WithConfigProvider` start option has been updated to accept a `ConfigProvider` argument (an interface) rather than `*ConfigProvider` (a concrete type). This is a breaking change for users of the `github.com/temporalio/ui-server/server/server_options` package.
Pointers to interfaces can be tricky to work with; see this thread for more background: https://stackoverflow.com/questions/44370277/type-is-pointer-to-interface-not-interface-confusion
1. Closes 
=> Remove config provider interface pointer

server/config/config.go
The `Config` struct now implements the `ConfigProvider` interface.
This is convenient for users who just want to supply hardcoded config, eg. [Temporalite](https://github.com/DataDog/temporalite).
1. Closes 
=> Implement ConfigProvider interface on *Config type

server/routes/api.go, server/server.go
When Auth is enabled and user is unauthenticated, immediately throws unauthorized error instead of making calls to Temporal Service
perf & security in case a TLS connection is treated as a way to avoid/not need user authentication
1. Closes 
=> Avoid making Temporal API calls if user unauthenticated

config/development.yaml, docker/config_template.yaml, server/config/config.go, server/routes/auth.go
Allows to configure generic OIDC Auth options
Support for provider specific scenarios, such as Auth0 invitation flow
1. Closes 
=> Support custom OIDC auth scenarios

server/routes/api.go
Exposes auth options names from the config, 
For example the auth config may have entries
- organization
- invitation
- audience
... to support invitation flow in case of Auth0
Let's UI know what additional options your auth flow expects
1. Closes 
=> Expose auth options through settings API

docker/config_template.yaml
Sets a default namespace when using docker image
Unless users would pass a `TEMPORAL_DEFAULT_NAMESPACE` when starting a docker image, UI would try to navigate by default to `<no value>` namespace 
1. Closes 
build & start the docker image
open http://localhost:8080/
expected: should navigate to http://localhost:8080/namespaces/default
=> Set dockerize default namespace

server/rpc/rpc.go
Incrased max gRPC API response size to 64mb
addressed #121
1. Closes 
Created a payload of 28mb size using https://github.com/temporalio/samples-go/tree/main/temporal-fixtures/largepayload
Verified that the page doesn't throw 429, also under ~4mb/s network: 
=> Increase gRPC receive max message size to 64mb

go.mod, go.sum
…teway
Switches to a fork of grpc-gateway that unescapes characters such as `/`
Address https://github.com/temporalio/ui/issues/392
1. Closes 
verified using canary data
=> Unescape characters in HTTP requests

config/development.yaml, docker/config_template.yaml, server/config/config.go, server/routes/api.go
Adds config option for Feedback URL
Allows to change Feedback button URL so that users can point to their internal channels
Partially addresses https://github.com/temporalio/ui/issues/502
1. Closes 
http://localhost:8080/api/v1/settings
```
{"Auth":{"Enabled":false,"Options":{
"Auth": {
"Enabled": false,
"Options": ["invitation", "audience", "organization"]
},
"DefaultNamespace": "default",
"ShowTemporalSystemNamespace": false,
"FeedbackURL": "https://custom-feedback-url",
"Codec": { "Endpoint": "", "PassAccessToken": false }
}
```
=> Allow customizing Feedback URL

server/codec/codec.go, server/routes/api.go
Adds API `http://localhost:8080/api/v1/settings/codec/:endpoint` that will overwrite Codec Endpoint set through config
useful when testing new implementations of codec 
1. Closes 
- Set `codec endpoint` through config to any value
- Open http://localhost:8080/api/v1/settings and verify that the endpoint matches config value
- POST `http://localhost:8080/api/v1/settings/codec/:555`
- Open http://localhost:8080/api/v1/settings and verify that the endpoint has changed to 555
5. Any docs updates needed?
=> Add API to set codec endpoint

server/server.go
Disabled `HTTPOnly` in CSRF cookie 
This rule enabled was breaking Terminate and Query functionalities as CSRF header is set via javascript on the client side
1. Closes 
Verified Terminate works
=> Disable HTTPOnly in CSRF cookie to fix write operations

.gitignore, server/api/handler.go, server/auth/auth.go, server/auth/oidc.go, server/routes/api.go, server/routes/auth.go
- Extracted auth related methods from routes to a reusable components
- Added auth related const values  
addressing tech debt and the ease of supporting ui server
1. Closes 
tested with google auth in a related PR https://github.com/temporalio/ui-server/pull/159 . Automated cloud testing WIP
=> Refactor auth for modularity

server/auth/auth.go
ensuring only a single auth header is set
grpc-gateway may forward authorization header. This could result in a duplication of auth header because the auth was also appended from a cookie/authorization header in the custom logic
1. Closes 
google oauth
cloud automated testing tbd
=> Avoid duplication of auth headers

server/auth/auth.go, server/auth/oidc.go, server/routes/auth.go
- Started sending ID Token in a `authorization-extras` header  
- Slightly reduced auth cookie size
- In some cases users have permissions set in ID token instead of the access token
1. Closes 
- google auth / verified both access token and ID token are sent with gRPC requests. 
- automated cloud testing tbd
=> Implement passing ID Token with API calls

.gitignore, server/server.go, server/server_options/server_option.go, server/server_options/server_options.go
Allows to set different session store through plugins
Cookie store may not work due to limitation of 4096 bytes per cookie. The change allows to use different stores such as filesystem and other stores that implement github.com/gorilla/sessions store
1. Closes 
- Ran ui-server w/o providing a plugin, verified that full `auth` and `auth-extras` tokens are stored as cookies
- Ran ui-server and provided `sessions.NewFilesystemStore` as a session store. Verified that `auth` and `auth-extras` cookies are now references to the session value. References are ~ 190-200 bytes
long term: Ideally switch the default store to GroupCache https://github.com/golang/groupcache
=> Support setting session store as plugin

cmd/server/main.go, config/development.yaml, docker/config_template.yaml, server/config/config.go
Adds configuration option to switch to filesystem store
Increases session store limit from 4KB to 64KB to resolve auth issues when `access token` or `ID token` are larger than 4KB 
1. Closes 
- Verified it switches stores when providing and not providing configuration for the filesystem store
- E2E for auth  
=> Support filesystem based session store

config/development.yaml, docker/config_template.yaml, server/api/handler.go, server/config/config.go
Adds config that disables write actions
Allows to disable Terminate button and other actions
1. Closes 
```
curl http://localhost:8080/api/v1/settings                                                                                                                                                             
{"Auth":{"Enabled":false,"Options":["audience","organization","invitation"]},"DefaultNamespace":"default","ShowTemporalSystemNamespace":false,"FeedbackURL":"","NotifyOnNewVersion":true,"Codec":{"Endpoint":"","AccessToken":""},"Version":"2.3.0","DisableWriteActions":false}
```
=> Add configuration to disable write actions

cmd/server/main.go, config/development.yaml, docker/config_template.yaml, plugins/forwardheaders/forwardheaders.go, server/config/config.go
Allows to specify headers that will be passed from HTTP requests to gRPC Temporal backend
Additional headers can be used for security and other use cases 
1. Closes 
tested passing
`TEMPORAL_FORWARD_HEADERS=X-Forwarded-For,X-Forwarded-Port` in docker image
=> Add configuration to forward HTTP headers

config/development.yaml, docker/config_template.yaml, server/config/config.go, server/routes/auth.go
Adds config that overrides the issuerUrl  computed by the providerUrl
In some cases, the provider URL is not the same as the issuerUrl, ie, in some multitenancy scenarios when we use FusionAuth or seems that in Azure too.
1. Closes #193
Tested using our FusionAuth IDP.
=> Add configuration to allow override the IssuerUrl

Dockerfile
Updates docker image to run as a non-root user. This PR recreates  https://github.com/temporalio/ui-server/pull/170 , which seems to have had some issues going through license validation. 
Address a requirement to run all images as non-root in a kubernetes cluster. 
1. Closes  #156
=> Fix docker non-root access

cmd/server/main.go, cmd/server/main_test.go
When running 2.5.0, the server would silently stop (no logs or error messages) with exit code 0 in the event there was an error processing configuration (no config found, bad value, etc). I fixed this by wrapping the error from `config.Load` in `cli.Exit`.
I also added error handling for any uncaught errors from the run in case there are other instances of this problem.
1. How was this tested:
Unit
1. Any docs updates needed?
No
=> don't swallow configuration error messages

server/csrf/skipper.go, server/csrf/skipper_test.go, server/server.go
- Allows HTTP requests with set `authorization` header to pass CSRF check
In case when API is hosted under different origin from the UI the existing CSRF rules block API POST/PUT/.. insecure HTTPs methods which result in Terminate/.. buttons to not work. The change allows the requests with Authorization header set to pass the CSRF check as it still protects against CSRF
1. Closes 
new unit tests
=> Enable authorization header as CSRF protection

config/base.yaml, config/development.yaml, docker/config_template.yaml, server/config/config.go, server/route/api.go, server/route/auth.go, server/route/health.go, server/route/openapi.go, server/route/public_path.go, server/route/ui.go, server/server.go
Allows serving UI under subpaths, ex `http://localhost:8080/subpath1/namespaces`
partially resolve https://github.com/temporalio/ui/issues/576
1. Closes 
Started and verified ui-server with `publicPath: /custom-path` set in `development.yml` 
Does not yet work with docker images. TBU https://github.com/temporalio/ui-server/pull/213
=> Support configuring UI public path

.gitignore, cmd/server/main.go, docker/config_template.yaml, go.mod, go.sum, server/api/handler.go, server/auth/auth.go, server/auth/auth_test.go, server/auth/oidc.go, server/config/config.go, server/headers/headers.go, server/route/api.go, server/route/auth.go, server/server.go, server/server_options/server_option.go, server/server_options/server_options.go
Moved user session to be stored client side
resolve #216 
Allows to scale UI horizontally by making ui-server stateless
1. Closes 
E2E: Verified that a user can login
Manual: Verified login and logout flows. Verified that API requests contain `authorization` and `authorization-extras` headers. Verified that codec requests contain `authorization` header 
=> Store user session in browser

e2e/README.md, e2e/package-lock.json, e2e/package.json, server/auth/auth.go
- Changed base64 encoding so it includes padding characters
- Set user auth cookie to strict mode for same site policy
- javascript `atob` requirements (e2e tests failing, the issue was reproing occasionally)
- security
1. Closes 
=> Stop removing padding in auth encoding to support atob

.github/workflows/docker-cloud.yml, .github/workflows/docker.yml
Updated GitHub Actions workflow triggering conditions to `released`
`published`: a release, pre-release, or draft of a release is published
`unpublished`: a release or pre-release is deleted
`created`: a draft is saved, or a release or pre-release is published without previously being saved as a draft
`edited`: a release, pre-release, or draft release is edited
`deleted`: a release, pre-release, or draft release is deleted
`prereleased`: a pre-release is created
`released`: a release is published, or a pre-release is changed to a release
More info: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#release
Current triggering conditions don't allow for creating a draft release and then publishing it.
=> Update GitHub Actions workflow triggering conditions

server/route/auth.go
Fixes "state did not match" error that could happen for an hour after user logging in in pre v2.8.0 and then upgraded to v2.8.0
1. Closes 
Started UI with v2.6.0 and logged in. 
Stopped v2.6.0
Started UI with v2.8.0 and logged in
=> Fix v2.8.0 auth upgrade scenario

server/headers/headers.go
Fixes forwarding `authorization-extras` header to Temporal Frontend
This header is sometimes used for authorization instead of `authorization` header
1. Closes 
Verified that Temporal Frontend reads `authorization-extras` header
=> Fix forwarding Authorization-Extras header

docker/README.md, docker/config_template.yaml
Added `TEMPORAL_AUTH_SCOPES` that allows to customize auth scopes when running in docker
resolve #210
1. Closes 
built & started docker with OIDC auth setup -> went through login flow. Verified that changing `TEMPORAL_AUTH_SCOPES` results in changes in `docker.yml`
```
docker run \
--network host \
-e TEMPORAL_ADDRESS=127.0.0.1:7233 \
-e TEMPORAL_UI_PORT=8080 \
-e TEMPORAL_AUTH_ENABLED=true \
-e TEMPORAL_AUTH_PROVIDER_URL=https://accounts.google.com \
-e TEMPORAL_AUTH_CLIENT_ID=xxx \
-e TEMPORAL_AUTH_CLIENT_SECRET=yyy \
-e TEMPORAL_AUTH_CALLBACK_URL=http://localhost:8080/auth/sso/callback \
-e TEMPORAL_AUTH_SCOPES=openid,email,profile \
ui
```
=> Add docker env to control OIDC auth scopes

server/config/config.go, server/route/ui.go, server/server.go
Added a config option to use a custom asset directory, replacing the bundled assets.
This makes it easy to test UI changes with `server start-dev`.
1. Closes 
Tested via Temporal CLI PR: `./temporal server start-dev --ui-asset-path $PWD/../ui/.vercel/output/static/` versus `./temporal server start-dev`. Confirmed the adjusted UI is served when the option is passed.
No.
=> Allow using a custom asset path, overriding the embedded UI assets.

.github/workflows/docker.yml
We now use a dockerhub Personal Access Token (PAT) instead of the account password
Over the weekend security changed our docker account to require MFA, so our automated processes need to use the PAT instead of the password
=> Use a dockerhub PAT instead of the account password

.github/workflows/on-release.yaml
Strip the v prefix from GitHub release tags when building Docker images
while preserving the full tag name for downstream dispatch payloads.
Pre automation the Docker image build process used the version tag name (e.g.,
`1.2.3`) as the image tag. Post automation the build process uses the GitHub
release tag name (e.g., `v1.2.3`) as the image tag. This change formats the tag
to adhere to the previous convention.
=> fix: Remove v prefix from Docker tags in release workflow

.github/actions/commit-changes/action.yaml, .github/workflows/on-commit-dispatch.yml, .github/workflows/on-release-dispatch.yml
Updates the commit-changes GitHub Action to use GitHub App authentication instead of default GITHUB_TOKEN to enable proper push permissions in workflow contexts.
The commit-changes action needs to push commits during automated workflows. Using the default GITHUB_TOKEN can have limitations for push operations in certain workflow contexts. This change ensures proper permissions by using a GitHub App token, following the same pattern already established in the on-release workflow.
- Added `app-id` and `private-key` inputs to the commit-changes action
- Added token generation step using `actions/create-github-app-token@v2`
- Set `GITHUB_TOKEN` environment variable in commit step to use generated token
- Updated both dispatch workflows to pass app credentials
The changes will be validated when …
=> DT-3284: Use GitHub App token for git push operations in workflows

.github/actions/commit-changes/action.yaml
Updates the commit-changes action to properly authenticate with GitHub CLI before pushing, addressing repository rule violations.
Push operations were failing with error: "Required workflow 'Check for CODEOWNERS' is not satisfied"
- Add separate "Configure Git" step that authenticates with gh CLI using the App token
- Use `temporal-cicd[bot]` as the commit user
- Remove GITHUB_TOKEN env var in favor of gh auth login
The changes will be validated when the next dispatch workflow runs after merging.
[DT-3284](https://temporalio.atlassian.net/browse/DT-3284)
[DT-3284]: https://temporalio.atlassian.net/browse/DT-3284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DT-3284: Fix GitHub App authentication for push operations

.github/actions/commit-changes/action.yaml, .github/workflows/on-commit-dispatch.yml, .github/workflows/on-release-dispatch.yml
Moves GitHub App authentication setup to the workflows themselves to ensure proper token usage throughout the entire workflow.
Push operations were failing with: "Required workflow 'Check for CODEOWNERS' is not satisfied"
The issue was that we need the GitHub App token from the very beginning of the workflow, including for the checkout step.
Following the pattern from temporal-worker-controller release workflow:
- Generate GitHub App token as first step in dispatch workflows  
- Use token for checkout with fetch-depth: 0
- Configure Git and gh CLI auth after checkout
- Simplify commit-changes action to only handle commits
The changes will be validated when the next dispatch workflow runs after merging.
[DT-3284](https://temporalio.atlassian.net/browse/DT-3284)
[DT-3284]: …
=> DT-3284: Fix GitHub App authentication flow in dispatch workflows
