cmd/server/main.go
config/base.yaml
config/development.yaml
go.mod
go.sum
server/config/config.go
server/config/loader.go
server/server.go
server/server_options/apply_func_container.go
server/server_options/server_option.go
server/server_options/server_options.go

Adds configuration options for UI server
Allows to configure the UI Server through a `yaml` based configurations files.
The design follows a similar Temporal Service feature https://github.com/temporalio/temporal/tree/master/common/config
1. Closes 
Verified the config files are read

Create config feature foundation

---

server/server.go
server/server_options/server_option.go
server/server_options/server_options.go

Applies `temporalGrpcAddress` and `port` to run on configs
Applies actual configs instead of hardcoded values
1. Closes 
Checking the values in Debug
Verifying through Swagger UI

Apply port and temporal frontent address settings

---

config/development.yaml
server/config/auth.go
server/config/config.go
server/routes/auth.go
server/server.go
server/server_options/server_option.go
server/server_options/server_options.go

Applies auth config provided in config `yaml` to the actual Auth feature
Applies actual configs instead of hardcoded values
1. Closes 
Configured an Auth provider and signed in using poc react app 
yes

Apply auth config to auth feature

---

config/development.yaml
go.mod
server/config/config.go
server/server.go

Encrypts session store with an auto-generated key
security improvements & compliance
1. Closes 

Secure session using auto-generated key

---

config/development.yaml
go.mod
server/config/config.go
server/routes/auth.go
server/server.go

Removes custom ~random generator for user authentication calls
Implements "github.com/gorilla/securecookie" as ~random generator instead
Use proper generator to reduce risks of ~random generator issues
1. Closes 
Verified ~random auth `state` and `nonce` are used when making auth calls

Replace custom random generator with external lib in auth 

---

Dockerfile
docker/README.md
docker/config_template.yaml
docker/start-ui-server.sh

- Adds `Dockerfile`.
- Adds support for `dockerize`.
Allows to run the UI in `docker`, make it part of other docker related workflows (automation, cicd, running in development, prod etc).
How was this tested:
Building and running locally.

Support docker and dockerize

---

Makefile
server/server.go

Disables UI build in makefile, as it's broken and currently not required
Unblocking devs who try to build the proj
1. Closes 
Built + ran server

Disable UI build due to broken build

---

.github/workflows/test.yml
Makefile
go.mod
server/config/loader_test.go

Adds CI pipeline for PRs unit testing
CI
1. Closes 
- tested the new unit tests
- github action is to be tested by the PR

Create github actions CI pipeline

---

.github/workflows/ci.yml
README.md

Added the CI status badge:
[![Unit Tests](https://github.com/temporalio/ui-server/actions/workflows/test.yml/badge.svg)](https://github.com/temporalio/ui-server/actions/workflows/test.yml)
improves CI status info visibility
1. Closes 

Add CI status badge

---

README.md

add some tips for m1 users in README

add some tips for m1 users in README

---

README.md

add notes on how to use with Docker

[Readme] add notes on how to use with Docker

---

server/server.go

Added XSS and other common security headers
security measurements
1. Closes 
verified the headers are set in the responses for same and cross origin

Add common security, XSS protection headers

---

server/server.go

- Adds CSRF header to accepted headers
- Sets single path for CSRF tokens to avoid multiplication of tokens
Fixes issues with CSRF preventing POST/DELETE/PUT requests with CORS
1. Closes 
Terminated workflows from a UI served under different Origin

Resolve CSRF preventing POST/DELETE requests with CORS

---

config/development.yaml

Fixes misspelling in development config file and unsets tls server name
the error was preventing running the server with development config
1. Closes 
Ran the server and verified UI loads data

Fix development config file

---

.github/workflows/update-ui.yml

some changes how git credentials are set to fix https://github.com/temporalio/ui-server/runs/4942045302?check_suite_focus=true#step:8:17
should fix the UI update pipeline git push 
1. Closes 
Ran similar steps manually https://github.com/temporalio/ui-server/commit/975c09a7b5acc795993ba2f274c9c919c8bb9180

Fix UI update pipeline push access

---

.github/workflows/docker.yml

Starts pushing Release images (when there is a release on github) to https://hub.docker.com/repository/docker/temporalio/ui 
Automating release process
1. Closes 
not tested

Start pushing docker release images to temporalio/ui

---

.github/workflows/docker.yml

Removed `id` tags from docker push github pipeline
they seem unnecessary and currently break the pipeline because they are not unique https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsid
1. Closes 

Remove docker push pipeline Id tags

---

.github/workflows/docker.yml

Adds context tags to fix docker pipeline
should fix the pipeline
1. Closes 
not tested

Fix docker push pipeline by refercing proper context

---

.github/workflows/docker.yml

Skips steps based on Commit Push or Release event type
speeds up docker pipeline
1. Closes 

Optimize docker build & push pipeline

---

server/routes/auth.go

Adds audience from config when authenticating against OIDC provider
Many OIDC providers distinct auth targets by an audience argument 
1. Closes 
Tested with Auth0 app

Support audience target in OIDC auth

---

config/development.yaml

- Set config reload interval to 1 minute
- Set namespace as 'default` (for visibility)
- updated auth config examples to refer to Auth0  
- removes the need to restart the ui-server at development when updating TLS configs
- Auth0 auth examples are better suited for configuring JWT permissions etc than the default google oidc experience 
1. Closes 

Update development config defaults

---

.github/workflows/update-ui.yml

Upgrades to go v1.18 in UI update pipeline
ui-server requires 1.18
1. Closes 

Upgrade go version to v1.18 in UI update pipeline

---

Dockerfile

Rebased docker image build step on top of temporalio/base-builder
base-* images are approved from security perspective & for consistency
1. Closes 

Rebase Docker image on temporalio/base-builder

---

server/routes/auth.go

Makes auth endpoints compatible with UI v1
Changes `/auth/sso/callback` to `/auth/sso_callback`
Make the same UI v1 OIDC configs work with ui v2
1. Closes 

Make auth endpoints compatible with UI v1

---

server/routes/auth.go

Added `/auth/sso/callback` endpoint back. This should be the default one and the one documented
consistency with HTTP API naming
1. Closes 

Add /auth/sso/callback endpoint back

---

server/routes/auth.go

returns users back to the initial UI page after the AUTH
UX improvement
1. Closes 
Tested with google and Auth0 invitation flow

Return user back to initial UI page after auth

---

Dockerfile

This will resolve multiple CVEs
1. Closes 

Change to newest version of base-server

---

config/development.yaml
docker/config_template.yaml
server/config/config.go
server/routes/api.go

Adds configuration to show temporal-system namespace in namespace selector
Exposes this through `/api/settings`
Some users wanted to see temporal-system namespace
Addresses https://github.com/temporalio/ui/issues/314
1. Closes 

Add configuration for showing temporal-system namespace

---

docker/config_template.yaml

fixed the syntax of dockerize config template
prettier syntax where double brackets are split with a space doesn't work with dockerize. This breaks docker images
1. Closes 
* ran dockerize on a template
* built an image and verified it starts up as expected 

Fix dockerize template syntax

---

config/development.yaml
docker/config_template.yaml
server/config/config.go
server/routes/api.go

Add codec endpoint support in config
For remote data converter

Add codec config

---

config/development.yaml

Added a comment clarifying CORS origin `localhost:3000` and why it in development.yaml   
It was confusing some users and why it's in development config
1. Closes 

Add CORS comment in development config

---

server/routes/auth.go
server/server.go

Set strict CSRF policy
Protecting against CSRF attacks
1. Closes 
tested with google auth + ngrok

Set strict defaults for CSRF

---

cmd/server/main.go
server/version/version.go

- Bumps the UI version tag to v0.15.0
- Starts outputting the correct version in `./ui-server --help` 
New release
1. Closes 

Bump version to v0.15.0

---

server/version/version.go

UI version 2.0.0

---

.github/workflows/test.yml
.github/workflows/update-ui.yml
Makefile

Change install-ui to use pnpm install

Use pnpm install

---

server/version/version.go

Bump to v2.0.1

---

server/auth/auth.go

Accept `authorization` header as an access-token for API requests
In some use cases the frontend may send the token as authorization header instead of in a cookie 
1. Closes 
Verified that the access-token is being read and set in gRPC calls. Tested with google auth. Cloud automated testing TBD

Accept `authorization` header as an access-token for API requests

---

README.md

Add configuration readme

---

server/server.go

Add HeaderAuthorization to AllowHeaders

Add HeaderAuthorization to allow-list for headers

---

cmd/server/main.go
go.mod
plugins/fs_config_provider/fs_config_provider.go
plugins/fs_config_provider/loader.go
server/api/handler.go
server/auth/auth.go
server/routes/api.go
server/routes/auth.go
server/rpc/tls.go
server/server.go
server/server_options/server_option.go
server/server_options/server_options.go
server/version/version.go

- Tagged v2.1.0
- Renamed module to github.com/temporalio/ui-server/v2
- New release
- go convention for module versions
1. Closes 

Tag v2.1.0 and rename module to v2

---

server/routes/auth.go

Started showing more auth error details
In some cases (seemingly with expired auth cookie?) users receive `unable to set user`. The change should help to better figure out auth issues
1. Closes 

Show more auth failure details

---

server/version/version.go

Update version.go to v2.1.2

---

.github/workflows/docker-cloud.yml
Makefile
cloud.Dockerfile

Adds GHA pipeline that builds images with Cloud target
can be useful for running ui-server locally against Temporal cloud 
1. Closes 
WIP

Add pipeline to build cloud images

---

.github/workflows/docker-cloud.yml

Update docker cloud build pipeline name

---

server/version/version.go

Update UI to v2.1.3

---

server/auth/auth.go

Started ignoring errors again returned by [`session`](https://echo.labstack.com/middleware/session/)
Session package may return an error with still a valid session object. Prior to https://github.com/temporalio/ui-server/pull/158/files#diff-956736512b3ccebfe50a90cfbae07b4db83167c9683213136ba809a07c3154a5L93 the error was ignored 
1. Closes 
Google + Auth0 auth
WIP cloud e2e testing

Address occasional auth error

---

Makefile

Switched to pnpm instead of npm when building the UI files
addresses `svelte-kit` not found when building locally
1. Closes 
ran the docker.yml action using act

Switch to pnpm when building UI

---

README.md

added short description
1. Closes 

Add ui-server README description

---

server/rpc/tls.go

Stops requiring CA cert for TLS connection
in some cases CA is not needed for TLS
1. Closes 

Remove requiring CA for TLS connection

---

server/version/version.go

Bump version to v2.2.1

---

server/version/version.go

Bump version to v2.2.2

---

.github/workflows/e2e.yml
.gitignore
e2e/global-setup.ts
e2e/package-lock.json
e2e/package.json
e2e/playwright.config.ts
e2e/tests/workflows.spec.ts

Added E2E tests - moved from cloud and adapted the config for OSS
QA
1. Closes 
new GHA

Add E2E tests - moved from cloud

---

server/version/version.go

The release will allow users to switch to filesystem session store 
1. Closes 

Bump version to v2.3.0

---

server/version/version.go

Bump version to v2.4.0

---

server/version/version.go

Bump version to v2.5.0

---

server/version/version.go

Bump version to v2.5.1

---

server/routes/health.go
server/server.go

It was add a new endpoint for health checking ui-server.
It's very useful for AWS ALB

Healthcheck endpoint

---

Makefile

replaced script that was manually finding test dirs with a built-in syntax
- simplify maintenance by using build-ins
- remove un-needed code (timeout etc is controlled by CI scripts)
1. Closes 
- ran `make` 
- GHA pipelines

Update makefile test syntax

---

server/config/auth.go
server/config/config.go
server/routes/auth.go

Add configuration comments

---

go.mod
go.sum

resolve https://github.com/temporalio/ui-server/issues/214
1. Closes 
E2E tests + further Mend updates

Address golang.org/x/net SVE

---

Dockerfile
cloud.Dockerfile

Removed `make install-submodules` from Docker files as it was failing to security
Should fix the Docker build pipelines
1. Closes 

Fix Docker build pipelines

---

cloud.Dockerfile

allows to run cloud image as non root
security measures
1. Closes 

Docker non-root access for cloud image

---

.github/workflows/docker-cloud.yml

Changed the Cloud image pipeline to produce image with a semver tag
direct correlation image:tag to a release
1. Closes 

Tag cloud image as semver instead of sha

---

server/route/ui.go

Add .gif asset handler

---

server/version/version.go

Bump version to v2.6.1

---

server/route/ui.go

`*.gif` didn't work for such path
1. Closes 

Route for animated Temporal logo

---

README.md

Added more GHA pipeline badges
Pipelines status visibility
1. Closes 

Add more GHA badges

---

server/version/version.go

Bump UI to v2.6.2

---

server/version/version.go

Bump version to v2.7.0

---

Dockerfile
cloud.Dockerfile

Bump base image versions

---

server/version/version.go

Bump version to v2.7.1

---

.github/workflows/e2e.yml
config/development.yaml
docker/config_template.yaml
server/config/config.go
server/config/config_provider_with_refresh.go

removed unused code
some leftovers
1. Closes 
tests

Clean unused code

---

server/route/auth.go

Sets auth `state` and `nonce` cookie with `Path: "/"`
Fixes attaching cookie to auth callback request when using Public Path feature
1. Closes 
Tested as described here https://github.com/temporalio/ui/pull/888

Fix auth when using Public Path

---

e2e/global-setup.ts

fix e2e test due to new auth flow

---

server/version/version.go

Update UI Version to 2.8.2

---

.github/workflows/docker-cloud.yml
.github/workflows/docker.yml
.github/workflows/e2e.yml
.github/workflows/test.yml
.github/workflows/update-ui.yml

Updated pipelines to use
- actions/setup-go@v3 with `go.mod` go version
- actions/checkout@v3
Improving stability of the pipelines
1. Closes 
CI

Retrieve go version in pipelines from go.mod

---

server/version/version.go

bump version to 2.9.1

---

.github/workflows/e2e.yml
.github/workflows/test.yml
.github/workflows/update-ui.yml

Added go & go modules caching 
CI perf
1. Closes 
CI

Add some caching in CI pipelines

---

docker/README.md

A link in a README file was updated.
To lessen the risk of not finding what we're looking for.

TW 219: update legacy links

---

config/development.yaml
docker/config_template.yaml
e2e/global-setup.ts
server/api/handler.go
server/config/config.go

Add config options for workflow actions
Some customers may want the ability to gate these features
1. Closes 
Ran locally and verified correct API response

add config options for workflow actions

---

e2e/tests/workflows.spec.ts

Update e2e test to check for accordion text
Fix e2e test with new UI

Update test for Workflow Execution with new accordion text

---

server/version/version.go

Bump version to 2.10.0

---

config/development.yaml
docker/config_template.yaml
server/api/handler.go
server/config/config.go

- Add a config option for disabling bulk actions in the UI
- So that when we can release this feature we only need to change a config and not make code changes
1. Closes 

add config option for disabling bulk actions

---

server/version/version.go

update UI version to 2.10.3
to release a new version of ui-server
1. Closes 

update UI version to 2.10.3

---

.github/workflows/docker.yml

Use a build arg to build a cloud image for release.

---

Dockerfile

Bumped docker base image version
To have the latest images
1. Closes 
No
CI
No

Bump docker base images

---

.github/workflows/docker.yml

Remove incorrect quoting from build arg.
This was causing the cloud-ui image to fail at startup.
1. Closes 
Ran the image with the env var set by hand to check that fixes the issue.

Remove incorrect quoting from build arg.

---

.github/workflows/test.yml

Bump go to 1.20 in test workflow

---

.github/workflows/test.yml

https://github.com/actions/setup-go/issues/355
1. Closes 

Use quotes for go version

---

Makefile

Remove build-grpc from Makefile

---

.github/workflows/release.yml
.goreleaser.yml

Added a Github action to build and attach binaries to releases. 
Facilitate deployments outside of Docker using released binaries.
This does not affect any existing workflows and does not require a change in the current release process.
1. Closes 

Produce binary archives for releases.

---

server/version/version.go

Update version.go to v2.37.2

---

server/version/version.go

Reverts temporalio/ui-server#316

Revert "Update version.go to v2.37.2"
